#
# The contents of this file are subject to the license and copyright
# detailed in the LICENSE and NOTICE files at the root of the source
# tree and available online at
#
# http://www.dspace.org/license/
#

# Docker Compose for running the DSpace Angular UI for testing/development
# Requires also running a REST API backend (either locally or remotely),
# for example via 'docker-compose-rest.yml'
networks:
  dspacenet:
services:
  dspace-angular:
    container_name: dspace-angular
    image: dspace/dspace-angular:dspace-7_x
    build:
      context: .
      dockerfile: Dockerfile
    entrypoint:
      - /bin/bash
      - '-c'
      - |
        nginx
        node ./dist/server/main.js
    working_dir: /app
    networks:
      dspacenet:
    ports:
    - published: 4000
      target: 80
    stdin_open: true
    tty: true
